Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::group(array("prefix" => "admin", "as"=>"admin."), function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

            //PRODUCTS
            Route::group(array("prefix" => "products", "as"=>"products."), function () {

                //CATEGORIES
                Route::group(array("prefix" => "categories","as"=>"categories."), function () {
                    Route::get("{id}/copy", array("as"=>"{id}.copy", "uses" => "CategoryController@copy"));
                    Route::any("api/table", array("as"=>"api.table", "uses" => "CategoryController@getDatatable"));
                    Route::any("rebuildTree", array("as"=>"rebuildTree", "uses" => "CategoryController@rebuildTree"));
                });
                Route::resource("categories", "CategoryController");

                //INFORMATION
                Route::group(array("prefix" => "information","as"=>"information."), function () {
                    Route::any("api/table", array("as"=>"api.table", "uses" => "InformationController@getDatatable"));
                    Route::any("api/articlerelationtable/{article_id?}", array("as"=>"api.articlerelationtable", "uses" => "InformationController@getArticleRelationTable"));
                    Route::any("api/productinformationrelation/{productid?}", array("as"=>"api.productinformationrelation.table", "uses" => "InformationController@getProductInformationRelationTable"));
                    Route::any("api/plantrelationtable/{plant_id?}", array("as"=>"api.plantrelationtable", "uses" => "InformationController@getPlantRelationTable"));
                });
                Route::resource("information", "InformationController");

                //API
                Route::group(array("prefix" => "api","as"=>"api."), function () {
                    Route::any("table", array("as"=>"table", "uses" => "ProductExtensionController@getDatatable"));
                    Route::any("tablerow", array("as"=>"tablerow", "uses" => "ProductExtensionController@getTableRow"));
                    Route::get("pim", array("as"=>"pim", "uses" => "ProductExtensionController@json"));
                    Route::get("xls", array("as"=>"xls", "uses" => "ProductExtensionController@json"));
                    Route::any("relation/table/{article_id?}", array("as"=>"relation.table", "uses" => "ProductExtensionController@getRelationDatatable"));
                    Route::any("table/mediarelation/{product_id?}", array("as"=>"table.mediarelation", "uses" => "ProductExtensionController@getMediaRelationTable"));
                    Route::any("table/plantrelation/{product_id?}", array("as"=>"table.plantrelation", "uses" => "ProductExtensionController@getPlantRelationTable"));
                    Route::any("table/productinformationrelation/{product_id?}", array("as"=>"table.productinformationrelation", "uses" => "ProductExtensionController@getProductInformationRelationTable"));
                    Route::post("productdeliveryrow", array("as"=>"productdeliveryrow", "uses" => "ProductExtensionController@getProductDeliveryRow"));
                });
                Route::get("{id}/copy/{country_id?}", array("as"=>"{id}.copy.{country_id}", "uses" => "ProductExtensionController@copy"));

                Route::get('/sendAvailableAgain_to_customers/{product_id}/{country_id}' , array("as"=>"sendAvailableAgain_to_customers" , "uses"=>"ProductExtensionController@testSendAvailableAgain_to_customers") );
            });

            //LABELS
            Route::group(array("prefix" => "labels","as"=>"labels."), function () {
                Route::any("api/table", array("as"=>"api.table", "uses" => "LabelController@getDatatable"));
            });
            Route::resource("labels", "LabelController");

            Route::resource("products", "ProductExtensionController");
        });
    });
});

Models/Label.php
<?php

namespace Dcms\Products\Models;

use App;
use Dcms\Core\Models\EloquentDefaults;

class Label extends EloquentDefaults
{
    protected $connection = 'project';
    protected $table = "products_labels";

    public function labeldetail()
    {
        return $this->hasMany('Dcms\Products\Models\Labeldetail', 'label_id', 'id');
    }

    public function products()
    {
        /*
        The first argument in belongsToMany() is the name of the class Productdata, the second argument is the name of the pivot table, followed by the name of the product_id column, and at last the name of the product_data_id column.
        */
        return $this->belongsToMany('Dcms\Products\Models\Product', 'products_to_products_labels', 'label_id', 'product_id');
    }
}

Http/Controllers/LabelController.php
<?php
namespace Dcms\Products\Http\Controllers;

use Dcms\Core\Http\Controllers\BaseController;
use Dcms\Core\Models\Languages\Language;
use Dcms\Products\Models\Label;
use Dcms\Products\Models\Labeldetail;
use Illuminate\Support\Str;
use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use DataTables;
use Auth;

class LabelController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // load the view and pass the categories
        return View::make('dcmsproducts::labels/index');
    }

    public function getDatatable()
    {
        $query = Labeldetail::query();
        if (intval(session('overrule_default_by_language_id')) > 0) {
            $query->where('language_id', intval(session('overrule_default_by_language_id')));
        }
        $query->get(['id', 'title', 'image', 'language_id', 'label_id']);

        return DataTables::of($query)
            ->addColumn('edit', function ($model) {
                return '<form method="POST" action="/admin/labels/' . $model->id . '" accept-charset="UTF-8" class="pull-right"> <input name="_token" type="hidden" value="' . csrf_token() . '"> <input name="_method" type="hidden" value="DELETE">
								<a class="btn btn-xs btn-default" href="/admin/labels/' . $model->label->id . '/edit"><i class="far fa-pencil"></i></a>
								<button class="btn btn-xs btn-default" type="submit" value="Delete this article" onclick="if(!confirm(\'Are you sure to delete this item?\\r\\nthis may delete more than 1 item\')){return false;};"><i class="far fa-trash-alt"></i></button>
							</form>';
            })
            ->addColumn('image', function ($model) {
                return '<img src="' . $model->image . '"/>';
            })
            ->addColumn('regio', function ($model) {
                return '<img src="/packages/Dcms/Core/images/flag-' . strtolower($model->language->country) . '.svg" style="height:auto; width:16px;" />';
            })
            ->rawColumns(['regio', 'edit', 'image'])
            ->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $languages = DB::connection("project")->table("languages")->select((DB::connection("project")->raw("'' as detail_id,'' as title, '' as description, '' as subtitle, '' as slug, '' as image")), "id", "id as language_id", "language", "country", "language_name")->get();

        // load the create form (app/views/categories/create.blade.php)
        return View::make('dcmsproducts::labels/form')
            ->with('languages', $languages);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        //	get the category
        $Label = Label::find($id);

        $languages = DB::connection("project")->select('
													SELECT language_id, languages.language, languages.country, languages.language_name, products_labels.id,products_labels.sort_id, products_labels_language.id as detail_id, products_labels_language.label_id, products_labels_language.title,  products_labels_language.subtitle, products_labels_language.slug, products_labels_language.description, products_labels_language.image
													FROM products_labels_language
													LEFT JOIN languages on languages.id = products_labels_language.language_id
													LEFT JOIN products_labels on products_labels.id = products_labels_language.label_id
													WHERE  languages.id is not null AND  label_id = ?
													UNION
													SELECT languages.id , language, country, language_name, \'\' ,\'\' ,\'\' ,\'\' ,\'\' ,\'\' ,\'\' ,\'\' ,\'\'
													FROM languages
													WHERE id NOT IN (SELECT language_id FROM products_labels_language WHERE label_id = ?) ORDER BY 1
													', [$id, $id]);

        return View::make('dcmsproducts::labels/form')
            ->with('Label', $Label)
            ->with('languages', $languages);
    }


    private function validateLabelForm()
    {
        $Languages = Language::all();
        //$rules = array('sort_id'=>'required|integer');
        $rules = [];
        foreach ($Languages as $Lang) {
            //			$rules['title.'.$Lang->id] = 'required';
            //$rules['image.'.$Lang->id] = 'required';
        }

        $validator = Validator::make(request()->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return Redirect::back()
                ->withErrors($validator)
                ->withInput();
        } else {
            return true;
        }
    }

    private function saveLabelProperties($labelid = null)
    {
        $newLabel = true;
        // do check if the given id is existing.
        if (!is_null($labelid) && intval($labelid) > 0) {
            $Label = Label::find($labelid);
        }

        if (!isset($Label) || is_null($Label)) {
            $Label = new Label;
        } else {
            $newLabel = false;
        }

        $oldSortID = null;
        if ($newLabel == false && !is_null($Label->sort_id) && intval($Label->sort_id) > 0) {
            $oldSortID = intval($Label->sort_id);
        }

        $Label->sort_id = request()->get("sort_id") ?: 0;
        $Label->filter = (request()->has('filter') && intval(request()->get('filter')) == 1)? 1 : 0;
        $Label->save();

        $sort_incrementstatus = "0"; //the default
        if (is_null($oldSortID) || $oldSortID == 0) {
            //update all where sortid >= input::sortid
            $updateLabels = Label::where('sort_id', '>=', $Label->sort_id)->where('id', '!=', $Label->id)->get(['id', 'sort_id']);
            $sort_incrementstatus = "+1";
        } elseif ($oldSortID > request()->get('sort_id')) {
            $updateLabels = Label::where('sort_id', '>=', $Label->sort_id)->where('sort_id', '<', $oldSortID)->where('id', '!=', $Label->id)->get(['id', 'sort_id']);
            $sort_incrementstatus = "+1";
        } elseif ($oldSortID < request()->get('sort_id')) {
            $updateLabels = Label::where('sort_id', '>', $oldSortID)->where('sort_id', '<=', $Label->sort_id)->where('id', '!=', $Label->id)->get(['id', 'sort_id']);
            $sort_incrementstatus = "-1";
        }

        if ($sort_incrementstatus <> "0") {
            if (isset($updateLabels) && count($updateLabels) > 0) {
                //$uInformation for object Information :: update the Information
                foreach ($updateLabels as $uLabel) {
                    if ($sort_incrementstatus == "+1") {
                        $uLabel->sort_id = intval($uLabel->sort_id) + 1;
                        $uLabel->save();
                    } elseif ($sort_incrementstatus == "-1") {
                        $uLabel->sort_id = intval($uLabel->sort_id) - 1;
                        $uLabel->save();
                    }
                }//end foreach($updateInformations as $Information)
            }//end 	if (count($updateLabels)>0)
        }//$sort_incrementstatus <> "0"

        return $Label;
    }

    private function saveLabelDetail(Label $Label, $givenlanguage_id = null)
    {
        $input = request()->all();

        $Labeldetail = null;

        foreach ($input["title"] as $language_id => $title) {
            if ((is_null($givenlanguage_id) || ($language_id == $givenlanguage_id)) && (strlen(trim($input['title'][$language_id])) > 0)) {
                $Labeldetail = null; // reset when in a loop
                $newDetail = true;

                if (intval($input["label_detail_id"][$language_id]) > 0) {
                    $Labeldetail = Labeldetail::find($input["label_detail_id"][$language_id]);
                }
                if (!isset($Labeldetail) || is_null($Labeldetail)) {
                    $Labeldetail = new Labeldetail;
                } else {
                    $newDetail = false;
                }

                $Labeldetail->language_id = $language_id;
                $Labeldetail->title = $input["title"][$language_id];
                $Labeldetail->subtitle = $input["subtitle"][$language_id];
                $Labeldetail->slug = Str::slug($input["title"][$language_id]);
                $Labeldetail->description = $input["description"][$language_id];
                $Labeldetail->image = $input["image"][$language_id];
                //$Labeldetail->admin 			= Auth::dcms()->user()->username;

                $Labeldetail->save();
                Label::find($Label->id)->labeldetail()->save($Labeldetail);
            }
        }

        return $Labeldetail;
    }


    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        if ($this->validateLabelForm() === true) {
            $Label = $this->saveLabelProperties();
            $this->saveLabelDetail($Label);

            // redirect
            Session::flash('message', 'Successfully created Label!');

            return Redirect::to('admin/labels');
        } else {
            return $this->validateLabelForm();
        }
    }


    /**
     * Update the specified resource in storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function update($id)
    {
        if ($this->validateLabelForm() === true) {
            $Label = $this->saveLabelProperties($id);
            $this->saveLabelDetail($Label);

            // redirect
            Session::flash('message', 'Successfully updated Label!');

            return Redirect::to('admin/labels');
        } else {
            return $this->validateLabelForm();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        //	Labeldetail::where('id', '=', $id)->delete();

resources/views/labels/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Labels</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li><a href="{!! URL::to('admin/products') !!}"><i class="far fa-boxes"></i> Products</a></li>
        <li><a href="{!! URL::to('admin/labels') !!}"><i class="far fa-tags"></i> Labels</a></li>
        @if(isset($Label))
            <li class="active"><i class="far fa-pencil"></i> Label {{ $Label->id }}</li>
        @else
            <li class="active"><i class="far fa-plus-circle"></i> Create Label</li>
        @endif
      </ol>
    </div>

    <div class="main-content">

    @if(isset($Label))
        {!! Form::model($Label, array('route' => array('admin.labels.update', $Label->id), 'method' => 'PUT')) !!}
    @else
        {!! Form::open(array('url' => 'admin/labels')) !!}
    @endif

    	<div class="row">
				<div class="col-md-12">
					<div class="main-content-block">

              @if($errors->any())
                <div class="alert alert-danger">{!! HTML::ul($errors->all()) !!}</div>
              @endif

              <div class="form-group">
                {!! Form::label('sort_id', 'Sort') !!}
                {!! Form::text('sort_id', (old('sort_id') ? old('sort_id') : (isset($Label)?$Label->sort_id:'')), array('class' => 'form-control')) !!}
              </div>
              
              <!-- #FILTER-->
              <div class="form-group">
                  {!! Form::checkbox('filter', '1', null, array('class' => 'form-checkbox','id'=>'filter'))  !!}
                  {!! Html::decode(Form::label('filter', 'Filter', array('class' => (isset($Label) && $Label->filter==1)?'checkbox active':'checkbox'))) !!}
              </div>
              
              <!-- #TYPE-->
              <div class="form-group">
                  <label for="labeltype">Type</label>
                  <select id="labeltype" name="label" class="form-control">
                      <option value="hobby" {{ (isset($Label) && $Label->type=="hobby")?'selected':'' }}>Hobby</option>
                      <option value="pro" {{ (isset($Label) && $Label->type=="pro")?'selected':'' }}>Pro</option>
                  </select>
              </div>

              @if(isset($languages))
                  <ul class="nav nav-tabs" role="tablist">
                    @foreach($languages as $key => $language)
                          <li class="{!! ((intval(session('overrule_default_by_language_id')) == intval($language->language_id)) ? 'active' : ((intval(session('overrule_default_by_language_id')) == 0 && $key == 0) ? 'active': '') ) !!}"><a href="{!! '#' . $language->language . '-' . $language->country !!}" role="tab" data-toggle="tab"><img src="{!! asset('/packages/Dcms/Core/images/flag-' . strtolower($language->country) . '.svg') !!}" width="16" height="16" /> {!! $language->language_name !!}</a></li>
                    @endforeach
                  </ul>

                  <div class="tab-content">
              @foreach($languages as $key => $information)

                    <div id="{!! $information->language . '-' . $information->country !!}" class="tab-pane {!! ((intval(session('overrule_default_by_language_id')) == intval($information->language_id)) ? 'active' : ((intval(session('overrule_default_by_language_id')) == 0 && $key == 0) ? 'active': '')) !!}">

                      {!!Form::hidden('label_detail_id[' . $information->language_id . ']', $information->detail_id) !!}

                      <div class="form-group">
                        {!! Form::label('title[' . $information->language_id . ']', 'Title') !!}
                        {!! Form::text('title[' . $information->language_id . ']', (old('title[' . $information->language_id . ']') ? old('title[' . $information->language_id . ']') : $information->title ), array('class' => 'form-control')) !!}
                      </div>

                      <div class="form-group">
                        {!! Form::label('subtitle[' . $information->language_id . ']', 'Subtitle') !!}
                        {!! Form::text('subtitle[' . $information->language_id . ']', (old('subtitle[' . $information->language_id . ']') ? old('subtitle[' . $information->language_id . ']') : $information->subtitle ), array('class' => 'form-control')) !!}
                      </div>

                      <div class="form-group">
                        {!! Form::label('description[' . $information->language_id . ']', 'Description') !!}
                        {!! Form::textarea('description[' . $information->language_id . ']', (old('description[' . $information->language_id . ']') ? old('description[' . $information->language_id . ']') : $information->description ), array('class' => 'form-control')) !!}
                      </div>

                       <div class="form-group">
                          {!! Form::label('image'.$information->language_id, 'Image') !!}
                          <div class="input-group">
                              {!! Form::text('image['.$information->language_id.']', (old('image[' . $information->language_id . ']') ? old('image[' . $information->language_id . ']') : $information->image ) , array('class' => 'form-control' , 'id'=>'image-'.$information->language_id)) !!}
                            <span class="input-group-btn">
                              {!! Form::button('Browse Server', array('id'=>'browse_image-'.$information->language_id, 'class' => 'btn btn-primary browse-server')) !!}
                            </span>
                          </div>
                        </div>
                    </div>

              @endforeach
                  </div>

              @endif

                {!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
                <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>

          </div>
        </div>
      </div>

      {!! Form::close() !!}

    </div>

@stop

@section("script")

<script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootstrap.min.js') !!}"></script>
<script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootstrap-datetimepicker.min.js') !!}"></script>
<link rel="stylesheet" type="text/css" href="{!! asset('/packages/Dcms/Core/css/bootstrap-datetimepicker.min.css') !!}">

<script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckeditor/ckeditor.js') !!}"></script>
<script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckeditor/adapters/jquery.js') !!}"></script>
<script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckfinder/ckfinder.js') !!}"></script>
<script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckfinder/ckbrowser.js') !!}"></script>

<script type="text/javascript">
$(document).ready(function() {

	//CKFinder for CKEditor
	CKFinder.setupCKEditor( null, '/ckfinder/' );


	//Browser --) $(this).attr("id")
	$(".browse-server").click(function() {
		var returnid = $(this).attr("id").replace("browse_","") ;
		BrowseServer( 'Images:/', returnid);
	})

	//CKEditor
	$("textarea[id^='description']").ckeditor();
	$("textarea[id^='body']").ckeditor();

	//Bootstrap Tabs
	$(".tab-container .nav-tabs a").click(function (e) {
		e.preventDefault();
		$(this).tab('show');
	})

	//Bootstrap Datepicker
	$(".date").datetimepicker({
		todayHighlight: true,
		autoclose: true,
		pickerPosition: "bottom-left"
	});

});
</script>

@stop

resources/views/labels/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Labels</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li><a href="{!! URL::to('admin/products') !!}"><i class="far fa-boxes"></i> Products</a></li>
        <li class="active"><i class="far fa-tags"></i> Labels</li>
      </ol>
    </div>

    <div class="main-content">
    	<div class="row">
				<div class="col-md-12">
					<div class="main-content-block">

  @if (Session::has('message'))
    <div class="alert alert-info">{!! Session::get('message') !!}</div>
  @endif

    <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/labels/create') !!}">Create new</a></div>

    <h2>Overview</h2>

        <table id="datatable" class="table table-hover table-condensed" style="width:100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Country</th>
                    <th></th>
                </tr>
            </thead>
        </table>

        <script type="text/javascript">
            $(document).ready(function() {
                oTable = $('#datatable').DataTable({
                    "pageLength": 50,
                    "processing": true,
                    "serverSide": true,
                    "ajax": "{{ route('admin.labels.api.table') }}",
                    "columns": [
                        {data: 'id', name: 'id'},
                        {data: 'title', name: 'title'},
                        {data: 'image', name: 'image', searchable: false},
                        {data: 'regio', name: 'regio', searchable: false},
                        {data: 'edit', name: 'edit', orderable: false, searchable: false}
                    ]
                });
            });
        </script>

        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

        <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

	      	</div>
      	</div>
      </div>
    </div>

@stop