Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::group(array("prefix" => "admin", "as"=>"admin."), function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

            //PRODUCTS
            Route::group(array("prefix" => "products", "as"=>"products."), function () {

                //CATEGORIES
                Route::group(array("prefix" => "categories","as"=>"categories."), function () {
                    Route::get("{id}/copy", array("as"=>"{id}.copy", "uses" => "CategoryController@copy"));
                    Route::any("api/table", array("as"=>"api.table", "uses" => "CategoryController@getDatatable"));
                    Route::any("rebuildTree", array("as"=>"rebuildTree", "uses" => "CategoryController@rebuildTree"));
                });
                Route::resource("categories", "CategoryController");

                //INFORMATION
                Route::group(array("prefix" => "information","as"=>"information."), function () {
                    Route::any("api/table", array("as"=>"api.table", "uses" => "InformationController@getDatatable"));
                    Route::any("api/articlerelationtable/{article_id?}", array("as"=>"api.articlerelationtable", "uses" => "InformationController@getArticleRelationTable"));
                    Route::any("api/productinformationrelation/{productid?}", array("as"=>"api.productinformationrelation.table", "uses" => "InformationController@getProductInformationRelationTable"));
                    Route::any("api/plantrelationtable/{plant_id?}", array("as"=>"api.plantrelationtable", "uses" => "InformationController@getPlantRelationTable"));
                });
                Route::resource("information", "InformationController");

                //API
                Route::group(array("prefix" => "api","as"=>"api."), function () {
                    Route::any("table", array("as"=>"table", "uses" => "ProductExtensionController@getDatatable"));
                    Route::any("tablerow", array("as"=>"tablerow", "uses" => "ProductExtensionController@getTableRow"));
                    Route::get("pim", array("as"=>"pim", "uses" => "ProductExtensionController@json"));
                    Route::get("xls", array("as"=>"xls", "uses" => "ProductExtensionController@json"));
                    Route::any("relation/table/{article_id?}", array("as"=>"relation.table", "uses" => "ProductExtensionController@getRelationDatatable"));
                    Route::any("table/mediarelation/{product_id?}", array("as"=>"table.mediarelation", "uses" => "ProductExtensionController@getMediaRelationTable"));
                    Route::any("table/plantrelation/{product_id?}", array("as"=>"table.plantrelation", "uses" => "ProductExtensionController@getPlantRelationTable"));
                    Route::any("table/productinformationrelation/{product_id?}", array("as"=>"table.productinformationrelation", "uses" => "ProductExtensionController@getProductInformationRelationTable"));
                    Route::post("productdeliveryrow", array("as"=>"productdeliveryrow", "uses" => "ProductExtensionController@getProductDeliveryRow"));
                });
                Route::get("{id}/copy/{country_id?}", array("as"=>"{id}.copy.{country_id}", "uses" => "ProductExtensionController@copy"));

                Route::get('/sendAvailableAgain_to_customers/{product_id}/{country_id}' , array("as"=>"sendAvailableAgain_to_customers" , "uses"=>"ProductExtensionController@testSendAvailableAgain_to_customers") );
            });

            //LABELS
            Route::group(array("prefix" => "labels","as"=>"labels."), function () {
                Route::any("api/table", array("as"=>"api.table", "uses" => "LabelController@getDatatable"));
            });
            Route::resource("labels", "LabelController");

            Route::resource("products", "ProductExtensionController");
        });
    });
});

Models/Product.php
<?php

namespace Dcms\Products\Models;

use Dcms\Core\Models\EloquentDefaults;

use Auth;

class Product extends EloquentDefaults
{
    protected $connection = 'project';
    protected $table  = "products";

    public function information()
    {
        return $this->belongsToMany('\Dcms\Products\Models\Information', 'products_to_products_information', 'product_id', 'product_information_id')->withTimestamps();
    }

    public function price()
    {
        return $this->belongsTo('\Dcms\Products\Models\Price', 'product_id');
    }

    public function labels()
    {
        return $this->belongsToMany('\Dcms\Products\Models\Label', 'products_to_products_labels', 'product_id', 'label_id');
    }

    public function productDeliveries()
    {
        return $this->hasMany('Dcms\Products\Models\ProductDelivery', 'product_id');
    }
}

Http/Controllers/ProductController.php
<?php

namespace Dcms\Products\Http\Controllers;

use DB;

use Auth;
use View;
use Input;
use Session;
use Redirect;
use Validator;
use DataTables;
use Illuminate\Support\Str;

use Dcms\Products\Models\Image;
use Dcms\Products\Models\Price;
use Dcms\Products\Models\Carrier;
use Dcms\Products\Models\Product;
use Dcms\Products\Models\Category;
use App\Http\Controllers\Controller;
use Dcms\Products\Models\Attachment;
use Dcms\Products\Models\Information;
use Dcms\Core\Models\Countries\Country;
use Dcms\Products\Models\ProductCarrier;
use Dcms\Products\Models\ProductOptions;
use Dcms\Products\Models\ProductToOptions;

class ProductController extends Controller
{
    public $informatationColumNames = [];
    public $informatationColumNamesDefaults = []; // TO DO - the input on the information tab are array based
    public $productColumNames = [];
    public $productColumnNamesDefaults = []; // e.g. checkboxes left blank will result in NULL database value, if this is not what you want, you can set e.g. array('checkbox_name'=>'0');
    public $extendgeneralTemplate = "";
    public $informationTemplate = "";
    public $information_group_id = "";

    public function __construct()
    {
        $this->middleware('permission:products-browse')->only('index');
        $this->middleware('permission:products-add')->only(['create', 'store']);
        $this->middleware('permission:products-edit')->only(['edit', 'update']);
        $this->middleware('permission:products-delete')->only('destroy');

        $this->informationColumNames = [
            'title'                 => 'information_name'
            , 'description'         => 'information_description'
            , 'description_short'   => 'information_description_short'
            , 'meta_description'    =>  'information_meta_description'
            , 'marketplace_description'    =>  'marketplace_description'
            , 'sort_id'             => 'information_sort_id'
            , 'product_category_id' => 'information_category_id'
            , 'url_slug'            => 'information_name',
        ];

        $this->productColumNames = [
            'online'           => 'online'
            , 'code'           => 'code'
            , 'eancode'        => 'eancode'
            , 'image'          => 'image'
            , 'volume'         => 'volume'
            , 'volume_unit_id' => 'volume_unit_id'
            , 'new'            => 'new'
        ];

        $this->productColumNames = array_merge($this->productColumNames, array('discontinued'=>'discontinued','matter_id'=>'matter_id', 'usage'=>'usage', 'usage_intent_id'=>'usage_intent_id','npk'=>'npk','order_quantity'=>'order_quantity','order_unit_id'=>'order_unit_id','order_stack_id'=>'order_stack_id','admission_region'=>'admission_region','admission_nr'=>'admission_nr','brick'=>'brick','width'=>'width','height'=>'height','depth'=>'depth'));
        $this->productColumnNamesDefaults = array_merge($this->productColumnNamesDefaults, array('new'=>'0','pro'=>'0','discontinued'=>'0'));

        $this->informationColumNames = array_merge($this->informationColumNames, array( 'new'=>'information_new', 'catalogue'=>'information_catalogue', 'composition'=>'information_composition' ,'composition_short'=>'information_composition_short' , 'guarantee'=>'information_guarantee',  'manual'=>'information_manual', 'period'=>'information_period', 'image'=>'information_image', 'doses'=>'information_doses', 'highpriority'=>'highpriority', 'megamenu'=>'megamenu'));
       
        $this->extendgeneralTemplate = null;
        $this->informationTemplate = null;
        $this->information_group_id = null;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return View::make('dcmsproducts::products/index');
    }

    /**
     * $priceRows contains an array of Price-Models
     *
     * @return the row to inject prices
     */
    public function getPriceRow($priceRows=array(), $forceEmpty = false)
    {
        $rowstring = "";

        $openbody = true;
        $closebody = true;
        if ($forceEmpty === true && empty($priceRows) === true) {
            $openbody = false;
            $closebody = false;
            $priceRows[] = (object) array();
        }

        foreach ($priceRows as $Price) {
            $pricetype_option = "";
            foreach (['retail-price','purchase-price','purchase-price-UOM','purchase-price-1UT','purchase-price-3UT','purchase-price-6UT','purchase-price-14UT','purchase-price-24UT','purchase-price-28UT', 'next season price' ] as $pricetypes => $pricetype) {
                $selected = "";
                if (isset($Price->price_type) && $pricetype ==$Price->price_type) {
                    $selected = "selected";
                }

                $pricetype_option .= '<option value="'.$pricetype.'" '.$selected.'>'.$pricetype.'</option>';
            }

            $country_option = "";

            $onlineChecked = "";
            if (isset($Price->online) && $Price->online == 1) {
                $onlineChecked = "checked";
            }

            foreach ($this->getCountries("array") as $countryid => $country) {
                $selected = "";
                if (isset($Price->country_id) && $countryid == $Price->country_id) {
                    $selected = "selected";
                }

                $country_option .= '<option value="' . $countryid . '" ' . $selected . '>' . $country . '</option>';
            }

            $tax_option = "";
            foreach ($this->getTaxClasses("array") as $taxid => $tax) {
                $selected = "";
                if (isset($Price->price_tax_id) && $taxid == $Price->price_tax_id) {
                    $selected = "selected";
                }

                $tax_option .= '<option value="'.$taxid.'" '.$selected.' >'.$tax.'</option>';
            }

            if ($openbody === true) {
                $rowstring .= '<tbody >';
            }

            //------------------------------------------------------------------------
            // 							TEMPLATE FOR THE PRICE ROW
            // 		the {INDEX} tag will be replaced in the form.blade, and this script to the attachment database id - or some text to identify its new
            //------------------------------------------------------------------------
            $rowstring .= ' <tr>
								<td>
									<select id="price-country-id[{INDEX}]" class="form-control" name="price-country-id[{INDEX}]">
										'.$country_option.'
									</select>
								</td>
								<td>
									<select id="price_type[{INDEX}]" class="form-control" name="price_type[{INDEX}]">
										'.$pricetype_option.'
									</select>
								</td>
								<td>
									<input id="price[{INDEX}]" name="price[{INDEX}]" class="form-control" type="text" value="'.(isset($Price->price)?$Price->price:"").'">
								</td>
								<td>
									<select id="price_valuta_id[{INDEX}]" name="price_valuta_id[{INDEX}]" class="form-control">
										<option value="1">euro</option>
									</select>
								</td>
								<td>
									<select id="price_tax_id[{INDEX}]" name="price_tax_id[{INDEX}]" class="form-control">
										' . $tax_option . '
									</select>
								</td>
								<td>
									<input type="checkbox" value="1" name="price_online[{INDEX}]" '.$onlineChecked.' />
								</td>
								<td><a class="btn btn-default pull-right delete-table-row" href=""><i class="far fa-trash-alt"></i></a></td>
							</tr>';

            if (isset($Price->id) && intval($Price->id) > 0) {
                $rowstring = str_replace("{INDEX}", $Price->id, $rowstring);
            }
            $openbody = false;
        }

        if ($closebody === true) {
            $rowstring .= '</tbody>';
        }

        return $rowstring;
    }

    /**
     * $mDefaults contains an array of Price-Models
     *
     * @return the row to inject prices
     */
    public function getAttachmentsRow($mDefaults = [], $forceEmpty = false, $languageToArray = false, $selectedLanguage_id = null)
    {
        $aRowString = [];
        $rowstring = "";

        $encloseBody = true;

        if ($forceEmpty === true && empty($mDefaults) === true) {
            $encloseBody = false;
            $mDefaults[] = (object) [];
        }

        foreach ($mDefaults as $Attachment) {
            $countrieslangauge_option = "";
            foreach ($this->getCountriesLanguages("array") as $language_id => $language_COUNTRY) {
                $selected = "";
                if (isset($Attachment->language_id) && $language_id == $Attachment->language_id) {
                    $selected = "selected";
                } elseif (isset($selectedLanguage_id) && !is_null($selectedLanguage_id) && $language_id == $selectedLanguage_id) {
                    $selected = "selected";
                }

                $countrieslangauge_option .= '<option value="' . $language_id . '" ' . $selected . ' class="optie ' . $selectedLanguage_id . '">' . $language_COUNTRY . '</option>';
            }

            $setTheLanguageID = null;
            if (isset($Attachment->language_id)) {
                $setTheLanguageID = $Attachment->language_id;
            } elseif (isset($selectedLanguage_id) && !is_null($selectedLanguage_id)) {
                $setTheLanguageID = $selectedLanguage_id;
            }

            //------------------------------------------------------------------------
            // 							TEMPLATE FOR THE PRICE ROW
            // 		the {INDEX} tag will be replaced in the form.blade, and this script to the attachment database id - or some text to identify its new
            //------------------------------------------------------------------------
            $rowstring .= ' <tr>
								<td>
									<div class="input-group">

resources/views/products/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Products</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-boxes"></i> Products</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('products-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('admin/products/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>


                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
	                    	<th>Code</th>
	                    	<th>EAN Code</th>
	        		<th>Title</th>
	        		<th>Category</th>
	                    	<th>Volume</th>
	                    	<th>Country</th>
	                    	<th>ID</th>
	                    	<th>Online</th>
	                    	<th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.products.api.table') }}",
                                "columns": [
					{data: 'code', name: 'products.code'},
					{data: 'eancode', name: 'products.eancode'},
					{data: 'title', name: 'products_information.title'},
					{data: 'catalogue', name: 'products_information.catalogue'},
					{data: 'volume', name: 'volume', searchable: false},
					{data: 'country', name: 'country', searchable: false},
					{data: 'id', name: 'id'},
					{data: 'online', name: 'online', searchable: false},
					{data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                    <script type="text/javascript">
                        $(document).ready(function () {

                            $(document).on("click", ".delete", function (e) {
                                bootbox.confirm("Are you sure?", function (result) {
                                    Example.show("Confirm result: " + result);
                                });
                            });

                        });
                    </script>

                    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootstrap.min.js') !!}"></script>
                    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootbox.min.js') !!}"></script>

                </div>
            </div>
        </div>
    </div>

@stop